-- 1. HANGHANGKHONG
CREATE TABLE HANGHANGKHONG (
    MAHANG   VARCHAR2(5) PRIMARY KEY,
    TENHANG  VARCHAR2(50),
    NGTL     DATE,
    DUONGBAY NUMBER
);

-- 2. CHUYENBAY
CREATE TABLE CHUYENBAY (
    MACB     VARCHAR2(10) PRIMARY KEY,
    MAHANG   VARCHAR2(5),
    XUATPHAT VARCHAR2(50),
    DIEMDEN  VARCHAR2(50),
    BATDAU   DATE,
    TGBAY    NUMBER,
    CONSTRAINT FK_CB_HHK FOREIGN KEY (MAHANG)
        REFERENCES HANGHANGKHONG(MAHANG)
);

-- 3. NHANVIEN
CREATE TABLE NHANVIEN (
    MANV      VARCHAR2(10) PRIMARY KEY,
    HOTEN     VARCHAR2(50),
    GIOITINH  VARCHAR2(5),
    NGSINH    DATE,
    NGVL      DATE,
    CHUYENMON VARCHAR2(20)
        CHECK (CHUYENMON IN ('Phi công', 'Tiếp viên'))
);

-- 4. PHANCONG
CREATE TABLE PHANCONG (
    MACB    VARCHAR2(10),
    MANV    VARCHAR2(10),
    NHIEMVU VARCHAR2(30),
    CONSTRAINT PK_PC PRIMARY KEY (MACB, MANV),
    CONSTRAINT FK_PC_CB FOREIGN KEY (MACB)
        REFERENCES CHUYENBAY(MACB),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MANV)
        REFERENCES NHANVIEN(MANV)
);

